version: "3.0"
services:
  db:
    image: mysql:5.7
    platform: linux/x86_64
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_USER: develop
        MYSQL_PASSWORD: develop
    ports:
        - 3306:3306
    volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/init:/docker-entrypoint-initdb.d
